version: '3'

services:
  web:
    build: https://github.com/EliezerJD/backRFID.git
    command: bash -c "pip3 install python-dotenv && pip3 install django-cors-headers && pip3 install djangorestframework && pip3 install psycopg2-binary && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: back
    volumes:
      - .:/back
    ports:
      - "8000:8000"