# Generated by Django 3.0.4 on 2020-03-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='idrfid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
